#!/bin/sh

cd $(dirname ${BASH_SOURCE[0]})
dir=$(pwd)

rm -rf /etc/acpi /etc/X11/xorg.conf.d
ln -sfv $dir/acpi /etc
ln -sfv $dir/xorg.conf.d /etc/X11

for service in "$dir/systemd/*"; do
    ln -sfv $service /etc/systemd/system/
    systemctl enable --now $service
done
